add permissions logic
Moovly/wordpress-plugin pull request #34
Opened 2021-11-08 12:11 UTC by michiel1995

2021-11-08 12:27 UTC, NielsCorneille requested changes

2021-11-08 12:27 UTC, NielsCorneille commented on src/Api/Routes/Project.php
> +        $firstRenders = array_count_values($renders) > 0 ? $renders[0] : null;
```suggestion
        $lastRender = $renders[0] ?? null;
```

2021-11-09 09:57 UTC, NielsCorneille approved these changes

2022-01-25 09:34 UTC, EliasDeVos approved these changes

2022-01-25 09:51 UTC, merged